version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    restart: always
    # Remova volumes para produção
    # volumes:
    #   - .:/app
